import { useState } from 'react'
import { geminiService } from '@/services/geminiService'

export const useGemini = () => {
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [streamingText, setStreamingText] = useState('')

  const run = async <T>(operation: () => Promise<T>) => {
    setIsLoading(true)
    setError(null)
    try {
      return await operation()
    } catch (error: any) {
      const message = error?.message || 'BFF AI workflow failed'
      setError(message)
      throw new Error(message)
    } finally {
      setIsLoading(false)
    }
  }

  return {
    isLoading,
    error,
    streamingText,
    analyzeImage: (imageUrl: string, prompt: string, analysisType?: string) =>
      run(() => geminiService.analyzeImage(imageUrl, prompt, analysisType)),
    generateText: (prompt: string, context?: string, options?: Record<string, unknown>) =>
      run(() => geminiService.generateText([prompt, context].filter(Boolean).join('\n'), options)),
    streamText: async (prompt: string, context?: string, onChunk?: (chunk: string) => void, options?: Record<string, unknown>) => {
      const response = await run(() => geminiService.streamText([prompt, context].filter(Boolean).join('\n'), options))
      const text = typeof response === 'string' ? response : response?.text || ''
      setStreamingText(text)
      if (text) onChunk?.(text)
      return response
    },
    analyzeComplaintImage: (imageUrl: string) => run(() => geminiService.analyzeComplaintImage(imageUrl)),
    analyzeWardInfrastructure: (satelliteImageUrl: string, wardData: any) =>
      run(() => geminiService.analyzeWardInfrastructure(satelliteImageUrl, wardData)),
    analyzeEligibility: (profile: any) => run(() => geminiService.analyzeEligibility(profile)),
    explainEligibility: (familyProfile: any, housingUnit: any) =>
      run(() => geminiService.explainEligibility(familyProfile, housingUnit)),
    generateDocumentChecklist: (familyProfile: any, housingUnit: any) =>
      run(() => geminiService.generateDocumentChecklist(familyProfile, housingUnit)),
    generateInfrastructureReport: async () => 'Infrastructure reports are generated by the BFF ward analysis workflow.',
    clearError: () => setError(null),
    resetStreamingText: () => setStreamingText(''),
  }
}

