import { complaintsApi } from '@/lib/api/complaintsApi.js'
import { housingApi } from '@/lib/api/housingApi.js'
import { wardsApi } from '@/lib/api/wardsApi.js'

class BffAiFacade {
  async analyzeComplaintImage(_photoUrl: string) {
    return {
      category: 'civic_infrastructure',
      severity: 'medium',
      confidence: 0,
      suggestedAction: 'Submitted to BFF complaint workflow for classification and routing.',
    }
  }

  async analyzeImage(_imageUrl: string, _prompt: string, analysisType = 'general') {
    return {
      analysisType,
      summary: 'Image analysis is handled by the NivasAI BFF and AI services.',
      confidence: 0,
    }
  }

  async generateText(prompt: string) {
    return `BFF-managed AI response queued for: ${prompt}`
  }

  async streamText(prompt: string) {
    return this.generateText(prompt)
  }

  async analyzeWardInfrastructure(_satelliteImageUrl: string, ward: any) {
    const response = await wardsApi.analyzeWard({
      id: ward.id,
      name: ward.name,
      lat: ward.coordinates?.center?.lat || ward.center?.lat,
      lng: ward.coordinates?.center?.lng || ward.center?.lng,
    })
    return {
      findings: response.analysis?.findings || response.analysis || {},
      confidence: response.analysis?.confidence || 0,
      fullResponse: response.analysis?.summary || 'Ward analysis completed through BFF.',
    }
  }

  async analyzeEligibility(profile: any) {
    const response = await housingApi.matchHousing(profile)
    return {
      explanation: response.result?.eligibility?.summary || 'Eligibility evaluated through BFF housing matching.',
      confidence: response.result?.eligibility?.approvalConfidence || 0,
    }
  }

  async explainEligibility(familyProfile: any, unit: any) {
    const response = await housingApi.matchHousing(familyProfile)
    const match = response.result?.matches?.find((item: any) => item.id === unit.id) || response.result?.matches?.[0]
    return match?.explanation || 'Eligibility explanation is generated by the BFF housing workflow.'
  }

  async generateDocumentChecklist(familyProfile: any) {
    const response = await housingApi.matchHousing(familyProfile)
    return response.result?.eligibility?.missingDocuments || []
  }

  async routeComplaint(complaintId: string, officerId?: string) {
    return complaintsApi.routeComplaint(complaintId, { officerId })
  }
}

export const geminiService = new BffAiFacade()

